---
- hosts: local
  become: yes
  gather_facts: no
  tasks:
  - name: Install tomcate
    action: yum name=tomcat state=installed
  - name: Waiting for port 8080 to listen
    wait_for:
      port: 8080
      state: started
