---
- hosts: web
  become: yes
  tasks:
  - name: Install apache
    yum:
     name: httpd
     state: latest
  - name: Create a file if does ot exists
    file:
      state: touch
      path: /var/www/html/index.html
    register: result
  - debug: var=result
  - name: if line not there add it
    lineinfile:
      state: present
      dest: /var/www/html/index.html
      line: Hostname={{ansible_hostname }}
  - name: restart apache
    service:
       name: httpd
       state: reloaded
       enabled: yes
