---
- hosts: test
  become: yes
  


  tasks:
  - name: crete a file nd assign permission 
    file:
      state: touch 
      path: /home/ansible/test6
  - name: Creat user 
    user:
      name: user1
      state: present

  - name: Implement ACL on host group test
    acl:
      path: /home/ansible/test6
      entity: user2
      etype: user
      permissions: rw
      state: present 
    register: acl_info
  - name: Get facl command
    command: getfacl /home/ansible/test6
    register: result
  - name: Create group
    group:
      name: grp4
      state: present
  - name: Implement ACL on host group test
    acl:
      path: /home/ansible/test6
      entity: grp4
      etype: group
      permissions: rw
      state: present 
    register: acl_info
      
     
  
