#############fetch - Fetches a file from remote nodes##########################
#This module works like copy, but in reverse. It is used for fetching files from remote machines and storing them locally in a 
#file tree, organized by hostname. Note that this module is written to transfer log files that might not be present, so a missing
#remote file won’t be an error unless fail_on_missing is set to ‘yes’.
---
- hosts: test
  become: yes
  
  tasks:
  - name: fetch file from remote hosts
    fetch:
    src: /etc/ntp.conf
    dest: /home/ansible/prefix-{{ inventory_hostname }}
       
       
       ########Allows you to override the default behavior of appending hostname/path/to/file to the destination. 
       #If dest ends with '/', it will use the basename of the source file, similar to the copy module. Obviously this is
       #only handy if the filenames are unique.
       
