##########################Auther: Umesh R################################
---
- hosts: tets
  become: yes
  
  tasks: 
  - name:  Synchronization of src on the control machine to dest on the remote hosts
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    
  - name: Synchronization using rsync protocol (push)
    synchronize:
    src: some/relative/path/
    dest: rsync://somehost.com/path/
    
  - name: Synchronization using rsync protocol (pull)
    synchronize:
    mode: pull
    src: rsync://somehost.com/path/
    dest: /some/absolute/path/
    
  - name: Synchronization using rsync protocol on delegate host (push)
    synchronize:
    src: /some/absolute/path/
    dest: rsync://somehost.com/path/
    delegate_to: delegate.host
    
  - name: Synchronization using rsync protocol on delegate host (pull)
    synchronize:
    mode: pull
    src: rsync://somehost.com/path/
    dest: /some/absolute/path/
    delegate_to: delegate.host
    
  - name: Synchronization without any --archive options enabled
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    archive: no
    
  - name: Synchronization with --archive options enabled except for --recursive
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    recursive: no
    
  - name: Synchronization with --archive options enabled except for --times, with --checksum option enabled
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    checksum: yes
    times: no
    ##########################################################
  - name: Synchronization without --archive options enabled except use --links
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    archive: no
    links: yes
    
  - name:  Synchronization of two paths both on the control machine
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
  delegate_to: localhost
    
  - name:  Synchronization of src on the inventory host to the dest on the localhost in pull mode
    synchronize:
    mode: pull
    src: some/relative/path
    dest: /some/absolute/path
    
  - name: Synchronization of src on delegate host to dest on the current inventory host.
    synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: delegate.host
    
  - name: Synchronize two directories on one remote host.
    synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: "{{ inventory_hostname }}"
    
  - name: Synchronize and delete files in dest on the remote host that are not found in src of localhost.
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    delete: yes
    recursive: yes
    
  - name: Synchronize using an alternate rsync command ####### This specific command is granted su privileges on the destination
    synchronize:
    src: some/relative/path
    dest: /some/absolute/path
    rsync_path: "su -c rsync"
    
# Example .rsync-filter file in the source directory
# - var       # exclude any path whose last part is 'var'
# - /var      # exclude any path starting with 'var' starting at the source directory
# + /var/conf # include /var/conf even though it was previously excluded
    
  - name: Synchronize passing in extra rsync options
    synchronize:
    src: /tmp/helloworld
    dest: /var/www/helloworld
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
