##########################Auther: Umesh R################################
---
- hosts: test
  become: yes
  
  tasks: 
  - name: Synchronization of src on the control machine to dest remote hosts
    synchronize:
      src: /home/ansible/chrony.j2
      dest: /tmp
    
#  - name: Synchronization using rsync protocol (push)
#    synchronize:
#      src: /home/ansible/chrony.j2
#      dest: rsync://umeshr19782.mylabserver.com/tmp
    
#  - name: Synchronization using rsync protocol (pull)
#    synchronize:
#      mode: pull
 #     src: rsync://umeshr19782.mylabserver.com/tmp/chrony.j2
  #    dest: /var/
    
  - name: Synchronization using rsync protocol on delegate host (push)
    synchronize:
      src: /home/ansible/chrony.j2
      dest: rsync://umeshr19782.mylabserver.com/tmp
    
  - name: Synchronization using rsync protocol on delegate host (pull)
    synchronize:
      mode: pull
      src: rsync://umeshr19782.mylabserver.com/tmp/chrony.j2
      dest: /var
    
