---
- hosts: test
  user: ansible
  sudo: yes
  tasks: 
  - name: Date/time when playbook starts
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install apache web server
    yum: pkg=httpd state=installed
    notify: Start HTTPD
  - name: Verif web service is running
    command: systemctl start httpd
    register: result
  - debug: var=result
  - name: install client software
    yum: pkg=telnet state=latest
  - name: Install lynx
    yum: pkg=lynx state=latest
  - name: Log all installed packages
    command: yum list installed
    register: installed_result
  - debug: var=installed_result
  - name: date/time when playbook ends
    command: /usr/bin/date
    register: timestamp_end
  - debug: var=timestamp_end
  
  handlers:
    - name: Start HTTPD
      service: name=httpd state=restarted
   


